import { EMAIL, TEXT } from "../utils/Const";

export const newUserConst = [
  {
    name: "name",
    label: "Name",
    dataKey: "name",
    type: TEXT,
    isRequired: true,
    requiredErrorMessage: "Please enter your name.",
  },
  {
    name: "phoneNumber",
    label: "Phone Number",
    dataKey: "PhoneNumber",
    type: TEXT,
    isRequired: true,
    requiredErrorMessage: "Please enter your phone number.",
  },
  {
    name: "companyName",
    label: "Company Name",
    dataKey: "companyName",
    type: TEXT,
    isRequired: true,
    requiredErrorMessage: "Please enter your name.",
  },
  {
    name: "companyAddress",
    label: "Company Address",
    dataKey: "companyAddress",
    type: TEXT,
    isRequired: true,
    requiredErrorMessage: "Please enter your address.",
  },
  {
    name: "email",
    label: "Email",
    dataKey: "email",
    type: TEXT,
    isRequired: true,
    requiredErrorMessage: "Please enter your email.",
  },
  {
    name: "password",
    label: "Password",
    type: "password",
    isRequired: true,
    requiredErrorMessage: "Please enter your password.",
  },
  {
    name: "confirmPassword",
    label: "Confirm Password",
    type: "password",
    isRequired: true,
    requiredErrorMessage: "Please confirm your password.",
  },

  {
    name: "role",
    label: "Role",
    dataKey: "role",
    type: "select",
    isRequired: true,
    options: [
      // { value: "BuilderFloorAdmin", label: "Builder Floor Admin" },
      { value: "ChannelPartner", label: "Channel Partner" },
      { value: "PropertyDealer", label: "Property Dealer" },
    ],
    requiredErrorMessage: "Please select a role.",
  },
  {
    name: "state",
    label: "state",
    dataKey: "state",
    type: "select",
    isRequired: true,
    options: [{ value: "harayana", label: "Harayana" }],
    requiredErrorMessage: "Please select a State.",
  },
  {
    name: "city",
    label: "city",
    dataKey: "city",
    type: "select",
    isRequired: true,
    options: [{ value: "gurgaon", label: "Gurgaon" }],
    requiredErrorMessage: "Please select a City.",
  },
];
